openapi: 3.1.0
info:
  version: 1.0.0
  title: TaskPro app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of TaskPro app
tags:
  - name: Tasks
    description: Operations about Tasks.
servers:
  - url: http://localhost:3000
  - url: https://task-manager-0qvm.onrender.com
paths:

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
